apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      labels:
        io.kompose.network/docker-rails-default: "true"
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: POSTGRES_HOST
              value: localhost
            - name: POSTGRES_PASSWD
              value: example
            - name: POSTGRES_USER
              value: postgres
          image: ghcr.io/neilkuan/docker-rails:v0.1.1
          name: app
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 1100m
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 256Mi
        - env:
            - name: POSTGRES_PASSWORD
              value: example
          image: postgres:alpine3.15
          name: db
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: 1100m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
      restartPolicy: Always
